import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: Colors.surface,
    paddingHorizontal: 20,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  headerTopRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerTitle: { fontSize: 32, fontWeight: '800', color: Colors.textPrimary },
  headerSubtitle: { fontSize: 12, color: Colors.textMuted, marginTop: 2, fontWeight: '500' },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  addBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.soft,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },

  // ── Toast ─────────────────────────────────────────────────────────────────
  toastBanner: {
    position: 'absolute',
    top: 90,
    left: 20,
    right: 20,
    zIndex: 50,
    backgroundColor: Colors.textPrimary,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    ...Shadows.soft,
  },
  toastText: { color: Colors.white, fontSize: 13, fontWeight: '600', textAlign: 'center' },
  toastError: { backgroundColor: Colors.error },

  // ── Segmented tabs ────────────────────────────────────────────────────────
  segmentRow: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 14,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 4,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    gap: 4,
  },
  segment: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 11,
    alignItems: 'center',
  },
  segmentActive: { backgroundColor: Colors.primaryLight },
  segmentText: { fontSize: 12, fontWeight: '700', color: Colors.textSecondary },
  segmentTextActive: { color: Colors.primary },

  // ── Search & filters ──────────────────────────────────────────────────────
  searchRow: { flexDirection: 'row', paddingHorizontal: 20, paddingTop: 12, gap: 10 },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingHorizontal: 12,
    height: 48,
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadows.soft,
  },
  searchInput: { flex: 1, fontSize: 13, color: Colors.textPrimary, paddingVertical: 0 },
  chipsRail: { flexGrow: 0, marginTop: 10 },
  chipsScroll: { paddingHorizontal: 20, gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  chipActive: { backgroundColor: Colors.primaryLight, borderColor: 'rgba(15,143,95,0.25)' },
  chipText: { fontSize: 12, fontWeight: '600', color: Colors.textSecondary },
  chipTextActive: { color: Colors.primary },

  // ── Lists & states ────────────────────────────────────────────────────────
  list: { paddingHorizontal: 20, paddingTop: 14, gap: 10 },
  loadMoreRow: { paddingVertical: 20, alignItems: 'center' },
  skeletonCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    gap: 8,
  },
  skeletonBlock: { backgroundColor: Colors.border, borderRadius: 8 },
  stateWrap: { alignItems: 'center', paddingVertical: 48, paddingHorizontal: 24 },
  stateIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  stateIconError: { backgroundColor: Colors.errorBg },
  stateTitle: { fontSize: 16, fontWeight: '700', color: Colors.textPrimary, marginBottom: 6 },
  stateSub: {
    fontSize: 13,
    color: Colors.textMuted,
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 16,
  },

  // ── Stock overview rows ───────────────────────────────────────────────────
  stockCard: {
    backgroundColor: Colors.surface,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadows.card,
  },
  stockTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  stockProductName: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary },
  stockVariantName: { fontSize: 12, color: Colors.textMuted, marginTop: 2 },
  lowStockBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: Colors.warningBg,
  },
  lowStockBadgeText: { fontSize: 10, fontWeight: '700', color: '#B45309' },
  outOfStockBadge: { backgroundColor: Colors.errorBg },
  outOfStockBadgeText: { color: Colors.error },
  healthyStockBadge: { backgroundColor: Colors.successBg },
  healthyStockBadgeText: { color: Colors.success },
  stockMetaRow: {
    flexDirection: 'row',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
  },
  stockMetaItem: { flex: 1 },
  stockMetaLabel: { fontSize: 10, color: Colors.textMuted, fontWeight: '600' },
  stockMetaValue: { fontSize: 13, color: Colors.textPrimary, fontWeight: '700', marginTop: 2 },

  // ── Batch cards ───────────────────────────────────────────────────────────
  batchCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  batchTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  batchProductName: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary },
  batchNumber: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
  statusBadge: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: 8 },
  statusBadgeText: { fontSize: 10, fontWeight: '700' },
  batchMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    rowGap: 8,
  },
  batchMetaItem: { width: '50%' },
  batchMetaLabel: { fontSize: 10, color: Colors.textMuted, fontWeight: '600' },
  batchMetaValue: { fontSize: 12, color: Colors.textPrimary, fontWeight: '700', marginTop: 1 },
  batchActions: { flexDirection: 'row', gap: 10, marginTop: 12 },

  // ── Transaction rows ──────────────────────────────────────────────────────
  txnCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  txnTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  txnTypeBadge: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: 8, backgroundColor: Colors.infoBg },
  txnTypeText: { fontSize: 10, fontWeight: '700', color: '#1565C0' },
  txnQty: { fontSize: 15, fontWeight: '800' },
  txnQtyPositive: { color: Colors.success },
  txnQtyNegative: { color: Colors.error },
  txnMetaRow: { marginTop: 8, gap: 4 },
  txnMetaText: { fontSize: 11, color: Colors.textMuted },
  txnDate: { fontSize: 11, color: Colors.textMuted, marginTop: 6 },

  // ── KPI strip ─────────────────────────────────────────────────────────────
  kpiScroll: { paddingHorizontal: 20, paddingTop: 14, gap: 10 },
  kpiCard: {
    minWidth: 100,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    gap: 4,
  },
  kpiCardActive: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  kpiValue: { fontSize: 20, fontWeight: '800', color: Colors.textPrimary },
  kpiValueWarn: { color: Colors.warning },
  kpiValueDanger: { color: Colors.error },
  kpiValueInfo: { color: Colors.info },
  kpiLabel: { fontSize: 11, fontWeight: '600', color: Colors.textMuted },

  // ── Stock health card (redesigned) ───────────────────────────────────────
  healthDot: { width: 10, height: 10, borderRadius: 5, marginTop: 3 },
  stockBarTrack: { height: 0, overflow: 'hidden' },
  stockBarFill: { height: 0 },
  stockInsightGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  stockInsightItem: {
    flex: 1,
    minWidth: 96,
    backgroundColor: Colors.background,
    borderRadius: 14,
    padding: 12,
  },
  stockInsightItemWide: {
    width: '100%',
    backgroundColor: Colors.primaryLight,
    borderRadius: 14,
    padding: 12,
  },
  stockActionText: { fontSize: 13, fontWeight: '800', color: Colors.primary, marginTop: 3 },
  stockSubRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 },
  stockSubText: { fontSize: 11, color: Colors.textMuted, fontWeight: '500' },
  stockSubValue: { fontSize: 12, color: Colors.textPrimary, fontWeight: '700' },

  expandedSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    gap: 8,
  },
  expandedSectionLabel: { fontSize: 10, fontWeight: '700', color: Colors.textMuted, letterSpacing: 0.6 },
  miniBatchCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.background,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  miniBatchLeft: { flex: 1 },
  miniBatchTitle: { fontSize: 12, fontWeight: '700', color: Colors.textPrimary },
  miniBatchSub: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
  expandedActions: { flexDirection: 'row', gap: 10, marginTop: 4 },

  // ── Expiry chip ───────────────────────────────────────────────────────────
  expiryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  expiryChipText: { fontSize: 10, fontWeight: '700' },
  expiryGood: { backgroundColor: Colors.successBg },
  expiryGoodText: { color: Colors.primaryDark },
  expirySoon: { backgroundColor: Colors.warningBg },
  expirySoonText: { color: '#B45309' },
  expiryUrgent: { backgroundColor: Colors.errorBg },
  expiryUrgentText: { color: Colors.error },

  // ── Batch progress bar ────────────────────────────────────────────────────
  batchProgressTrack: { height: 0, overflow: 'hidden' },
  batchProgressFill: { height: 0 },
  batchSummaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 },
  batchSummaryText: { fontSize: 11, color: Colors.textMuted, fontWeight: '500' },

  // ── Activity timeline ─────────────────────────────────────────────────────
  dayHeader: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textMuted,
    marginTop: 6,
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  activityCard: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    gap: 12,
    alignItems: 'flex-start',
  },
  activityIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityTitle: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
  activityMeta: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
  activityNote: { fontSize: 11, color: Colors.textSecondary, marginTop: 3, fontStyle: 'italic' },
  activityRight: { alignItems: 'flex-end' },
  activityQty: { fontSize: 15, fontWeight: '800' },
  activityTime: { fontSize: 10, color: Colors.textMuted, marginTop: 4 },

  // ── FAB + speed dial ──────────────────────────────────────────────────────
  fab: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.strong,
  },
  speedDialOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  speedDialItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    gap: 10,
    ...Shadows.soft,
  },
  speedDialIcon: {
    width: 32,
    height: 32,
    borderRadius: 9,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  speedDialLabel: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
});
