import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.surface },
  backButton: { padding: 8, marginRight: 8, borderRadius: 12, backgroundColor: Colors.background },
  headerText: { flex: 1 },
  title: { fontSize: 18, fontWeight: '800', color: Colors.textPrimary },
  subtitle: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  scrollContent: { padding: 16 },
  statsSummaryGrid: { flexDirection: 'row', gap: 8, marginBottom: 20 },
  summaryCard: { flex: 1, backgroundColor: Colors.surface, borderRadius: 16, padding: 12, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', ...Shadows.soft, alignItems: 'center' },
  summaryLabel: { fontSize: 10, color: Colors.textSecondary, fontWeight: '600', textAlign: 'center' },
  summaryVal: { fontSize: 18, fontWeight: '800', marginTop: 4 },
  sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 12 },
  sectionHeaderTitle: { fontSize: 15, fontWeight: '800', color: Colors.textPrimary },
  emptyCard: { backgroundColor: Colors.surface, borderRadius: 16, padding: 16, alignItems: 'center', borderWidth: 1, borderColor: Colors.border, marginBottom: 16 },
  emptyText: { fontSize: 12, color: Colors.textSecondary, textAlign: 'center' },
  alertCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: 'rgba(242, 169, 59, 0.05)', borderWidth: 1, borderColor: 'rgba(242, 169, 59, 0.3)', padding: 12, borderRadius: 16, marginBottom: 8, ...Shadows.soft },
  alertProduct: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
  alertInfo: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  boldText: { fontWeight: '700', color: Colors.error },
  searchBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border, borderRadius: 16, paddingHorizontal: 12, height: 40, marginBottom: 12, ...Shadows.soft },
  searchInput: { flex: 1, fontSize: 12, color: Colors.textPrimary, fontWeight: '500' },
  productStockList: { gap: 8, marginBottom: 20 },
  adjustStockCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.surface, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', padding: 12, borderRadius: 18, ...Shadows.soft },
  adjustProductName: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
  adjustProductStock: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  stockCountText: { fontWeight: '800', color: Colors.primary },
  adjustControls: { flexDirection: 'row', gap: 4 },
  qtyControlBtn: { paddingHorizontal: 8, paddingVertical: 6, borderRadius: 10, justifyContent: 'center', alignItems: 'center', minWidth: 32 },
  qtyControlText: { fontSize: 10, fontWeight: '700' },
  historyCard: { backgroundColor: Colors.surface, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', paddingHorizontal: 14, ...Shadows.soft, marginBottom: 20 },
  historyRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border },
  historyDot: { width: 6, height: 6, borderRadius: 3, marginRight: 10 },
  historyText: { fontSize: 12, fontWeight: '700', color: Colors.textPrimary },
  historySub: { fontSize: 10, color: Colors.textSecondary, marginTop: 2 },
  historyDate: { fontSize: 9, color: Colors.textSecondary, alignSelf: 'flex-start', marginTop: 2 },
  sheetContent: { padding: 16 },
  formLabel: { fontSize: 12, fontWeight: '600', color: Colors.textPrimary, marginBottom: 6 },
  formInput: { borderWidth: 1, borderColor: Colors.border, borderRadius: 12, paddingHorizontal: 12, height: 44, fontSize: 13, color: Colors.textPrimary, backgroundColor: Colors.background, marginBottom: 16 },
  reasonTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  reasonPill: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 14, backgroundColor: Colors.background, borderWidth: 1, borderColor: Colors.border },
  activeReasonPill: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  reasonPillText: { fontSize: 11, fontWeight: '600', color: Colors.textSecondary },
  activeReasonPillText: { color: Colors.white },
});
