import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export const blobStyles = StyleSheet.create({
  b1: { position: 'absolute', top: -40, right: -40, width: 160, height: 160, borderRadius: 80, backgroundColor: 'rgba(255,255,255,0.07)' },
  b2: { position: 'absolute', bottom: -30, left: 40, width: 110, height: 110, borderRadius: 55, backgroundColor: 'rgba(255,255,255,0.05)' },
});

export default StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.background },
  scroll: { paddingBottom: 120 },
  hero: { backgroundColor: Colors.primary, paddingHorizontal: 20, paddingBottom: 34, overflow: 'hidden', borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  heroRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  logoBox: { width: 44, height: 44, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.18)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)' },
  logoLetter: { fontSize: 19, fontWeight: '800', color: Colors.white },
  greeting: { fontSize: 12, color: 'rgba(255,255,255,0.65)', fontWeight: '500' },
  storeName: { fontSize: 20, fontWeight: '800', color: Colors.white, marginTop: 1 },
  roleBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(255,255,255,0.16)', borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2, marginTop: 4 },
  roleBadgeText: { fontSize: 9, fontWeight: '700', color: 'rgba(255,255,255,0.85)', letterSpacing: 0.4 },
  headerBtn: { width: 38, height: 38, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.13)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)' },
  metricStrip: { flexDirection: 'row', backgroundColor: 'rgba(255,255,255,0.12)', borderRadius: 16, paddingVertical: 14, paddingHorizontal: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)' },
  metricItem: { flex: 1, alignItems: 'center' },
  metricVal: { fontSize: 19, fontWeight: '800', color: Colors.white },
  metricLbl: { fontSize: 11, color: 'rgba(255,255,255,0.6)', marginTop: 3, fontWeight: '500' },
  metricDivider: { width: 1, backgroundColor: 'rgba(255,255,255,0.18)', marginVertical: 4 },
  floatRow: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, marginTop: -14, zIndex: 10 },
  floatCard: { backgroundColor: Colors.surface, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: Colors.border, ...Shadows.card },
  statusPulseRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 6 },
  statusChip: { fontSize: 11, fontWeight: '800', letterSpacing: 0.6 },
  statusTitle: { fontSize: 14, fontWeight: '600', color: Colors.textPrimary },
  revLabel: { fontSize: 10, fontWeight: '700', color: Colors.textMuted, letterSpacing: 0.5, textTransform: 'uppercase', marginBottom: 4 },
  revValue: { fontSize: 32, fontWeight: '800', color: Colors.textPrimary },
  revGrowthRow: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 4 },
  revGrowthText: { fontSize: 12, fontWeight: '600', color: Colors.success },
  kpiRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, marginTop: 12 },
  kpiCard: { flex: 1, backgroundColor: Colors.surface, borderRadius: 16, padding: 12, alignItems: 'center', gap: 4, borderWidth: 1, borderColor: Colors.border, ...Shadows.soft },
  kpiVal: { fontSize: 20, fontWeight: '800', color: Colors.textPrimary },
  kpiLbl: { fontSize: 10, fontWeight: '500', color: Colors.textMuted, textAlign: 'center' },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, marginTop: 24, marginBottom: 10 },
  sectionTitle: { fontSize: 20, fontWeight: '800', color: Colors.textPrimary },
  card: { backgroundColor: Colors.surface, marginHorizontal: 16, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: Colors.border, ...Shadows.card },
  actionsScroll: { paddingHorizontal: 16, gap: 8 },
  actionBtn: { alignItems: 'center', gap: 7, width: 68 },
  actionIcon: { width: 52, height: 52, borderRadius: 16, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(15,143,95,0.18)' },
  actionLabel: { fontSize: 11, fontWeight: '600', color: Colors.textSecondary, textAlign: 'center' },
  healthBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.accentLight, paddingHorizontal: 9, paddingVertical: 3, borderRadius: 20 },
  healthBadgeText: { fontSize: 11, fontWeight: '700', color: Colors.accent },
  perfRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 0, backgroundColor: Colors.background, borderRadius: 14, padding: 14 },
  perfLabel: { fontSize: 13, fontWeight: '500', color: Colors.textSecondary },
  perfVal: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
  viewAll: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  viewAllText: { fontSize: 12, fontWeight: '700', color: Colors.primary },
  orderCard: { marginBottom: 10, gap: 12 },
  orderTop: { flexDirection: 'row', alignItems: 'center' },
  orderAvatar: { width: 38, height: 38, borderRadius: 12, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center' },
  orderAvatarText: { fontSize: 15, fontWeight: '800', color: Colors.primary },
  orderName: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary },
  orderMeta: { fontSize: 11, color: Colors.textMuted, marginTop: 1 },
  orderAmount: { fontSize: 15, fontWeight: '800', color: Colors.textPrimary },
  statusPill: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 20 },
  statusPillText: { fontSize: 11, fontWeight: '700' },
  orderMeta2Row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 4, borderTopWidth: 1, borderTopColor: Colors.borderLight },
  orderPayText: { fontSize: 12, color: Colors.textMuted },
  orderActions: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  viewDetailsBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 8, borderRadius: 12, backgroundColor: Colors.primaryLight },
  viewDetailsBtnText: { fontSize: 13, fontWeight: '600', color: Colors.primary },
  emptyState: { alignItems: 'center', paddingVertical: 32, gap: 8 },
  emptyTitle: { fontSize: 15, fontWeight: '700', color: Colors.textSecondary },
  emptySubtitle: { fontSize: 12, color: Colors.textMuted },
  livePill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Colors.successBg, paddingHorizontal: 9, paddingVertical: 3, borderRadius: 20 },
  livePillText: { fontSize: 11, fontWeight: '700', color: Colors.success },
  activityRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10 },
  activityRowBorder: { borderBottomWidth: 1, borderBottomColor: Colors.borderLight },
  activityIcon: { width: 30, height: 30, borderRadius: 9, backgroundColor: Colors.surfaceElevated, alignItems: 'center', justifyContent: 'center' },
  activityLabel: { fontSize: 13, fontWeight: '600', color: Colors.textPrimary },
  activityTime: { fontSize: 11, color: Colors.textMuted, marginTop: 1 },
});
