import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.surface },
  backButton: { padding: 8, marginRight: 8, borderRadius: 12, backgroundColor: Colors.background },
  headerText: { flex: 1 },
  title: { fontSize: 18, fontWeight: '800', color: Colors.textPrimary },
  subtitle: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  scrollContent: { padding: 16 },
  radarCard: { backgroundColor: Colors.surface, borderRadius: 24, padding: 16, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', ...Shadows.soft, marginBottom: 20, alignItems: 'center' },
  radarHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, alignSelf: 'flex-start' },
  radarTitle: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary },
  radarSubtitle: { fontSize: 11, color: Colors.textSecondary, alignSelf: 'flex-start', marginTop: 2, marginBottom: 16 },
  radarWrapper: { width: 230, height: 230, borderRadius: 115, backgroundColor: 'rgba(0, 109, 119, 0.02)', borderWidth: 1.5, borderColor: Colors.border, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  radarCircleContainer: { width: 220, height: 220, borderRadius: 110, backgroundColor: '#FAFDFD', overflow: 'hidden', position: 'relative' },
  radarSweep: { position: 'absolute', width: 220, height: 220, left: 0, top: 0, justifyContent: 'center', alignItems: 'center' },
  sweepLine: { width: 2, height: 110, backgroundColor: 'rgba(0, 109, 119, 0.4)', bottom: 55 },
  riderPin: { position: 'absolute', width: 12, height: 12, borderRadius: 6, borderWidth: 1.5, borderColor: Colors.white, justifyContent: 'center', alignItems: 'center', ...Shadows.medium },
  pingAnimation: { width: 20, height: 20, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(34, 181, 115, 0.4)', position: 'absolute' },
  legend: { flexDirection: 'row', gap: 12, borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: 12, width: '100%', justifyContent: 'space-around' },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { fontSize: 10, color: Colors.textSecondary, fontWeight: '600' },
  listHeader: { fontSize: 15, fontWeight: '800', color: Colors.textPrimary, marginBottom: 12 },
  fleetList: { gap: 10 },
  driverCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.surface, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', padding: 14, borderRadius: 20, ...Shadows.soft },
  row: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  driverName: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary },
  idBadge: { backgroundColor: 'rgba(0, 109, 119, 0.06)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  idBadgeText: { fontSize: 9, color: Colors.primary, fontWeight: '700' },
  driverPhone: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  statsRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  statMini: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  statMiniText: { fontSize: 10, color: Colors.textSecondary, fontWeight: '600' },
  statDivider: { width: 1, height: 10, backgroundColor: Colors.border, marginHorizontal: 6 },
  driverActions: { alignItems: 'flex-end', gap: 8 },
  statusToggle: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statusToggleText: { fontSize: 11, fontWeight: '700' },
  switch: { transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }] },
  callButton: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: Colors.primary, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, backgroundColor: Colors.background },
  callButtonText: { fontSize: 11, fontWeight: '700', color: Colors.primary },
});
