import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.surface },
  backButton: { padding: 8, marginRight: 8, borderRadius: 12, backgroundColor: Colors.background },
  headerText: { flex: 1 },
  title: { fontSize: 18, fontWeight: '800', color: Colors.textPrimary },
  subtitle: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  scrollContent: { padding: 16 },
  metricsGrid: { flexDirection: 'row', gap: 12, marginBottom: 20 },
  metricCard: { flex: 1, backgroundColor: Colors.surface, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', ...Shadows.soft },
  iconBg: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  metricLabel: { fontSize: 12, color: Colors.textSecondary, fontWeight: '500' },
  metricValue: { fontSize: 22, fontWeight: '800', color: Colors.textPrimary, marginTop: 4 },
  metricSub: { fontSize: 10, color: Colors.textSecondary, marginTop: 2 },
  sectionHeader: { marginBottom: 12, marginTop: 8 },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: Colors.textPrimary },
  sectionSubtitle: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  chartTabs: { flexDirection: 'row', backgroundColor: 'rgba(102, 112, 133, 0.05)', padding: 4, borderRadius: 12, marginBottom: 12 },
  chartTab: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  activeChartTab: { backgroundColor: Colors.surface, ...Shadows.soft },
  chartTabText: { fontSize: 12, color: Colors.textSecondary, fontWeight: '600' },
  activeChartTabText: { color: Colors.primary },
  chartCard: { backgroundColor: Colors.surface, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', ...Shadows.soft, marginBottom: 20 },
  chartCardTitle: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary, marginBottom: 8 },
  chartStatsRow: { flexDirection: 'row', justifyContent: 'space-around', borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: 12, marginTop: 8 },
  chartStatLabel: { fontSize: 10, color: Colors.textSecondary, textAlign: 'center' },
  chartStatValue: { fontSize: 12, fontWeight: '700', color: Colors.textPrimary, marginTop: 2, textAlign: 'center' },
  topProductsList: { backgroundColor: Colors.surface, borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', ...Shadows.soft },
  productRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border },
  productRank: { flexDirection: 'row', alignItems: 'center', width: 32 },
  rankText: { fontSize: 11, fontWeight: '700', color: Colors.textSecondary, marginLeft: 2 },
  productImg: { width: 44, height: 44, borderRadius: 10, backgroundColor: Colors.background, marginRight: 12 },
  productDetails: { flex: 1 },
  productName: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
  productSales: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  productEarnings: { alignItems: 'flex-end' },
  earningsVal: { fontSize: 13, fontWeight: '800', color: Colors.primary },
  earningsLabel: { fontSize: 10, color: Colors.textSecondary, marginTop: 2 },
});
