import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.surface },
  backButton: { padding: 8, marginRight: 8, borderRadius: 12, backgroundColor: Colors.background },
  headerText: { flex: 1 },
  title: { fontSize: 18, fontWeight: '800', color: Colors.textPrimary },
  subtitle: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  topContainer: { backgroundColor: Colors.surface, paddingHorizontal: 16, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: Colors.border },
  searchBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.background, borderWidth: 1, borderColor: Colors.border, borderRadius: 14, paddingHorizontal: 12, height: 40, marginTop: 8 },
  searchInput: { flex: 1, fontSize: 13, color: Colors.textPrimary, fontWeight: '500' },
  filterScroller: { paddingVertical: 8, gap: 8 },
  filterPill: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 14, backgroundColor: Colors.background, borderWidth: 1, borderColor: Colors.border },
  activeFilterPill: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  filterPillText: { fontSize: 11, fontWeight: '600', color: Colors.textSecondary },
  activeFilterPillText: { color: Colors.white },
  scrollContent: { padding: 16, gap: 12 },
  emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
  emptyTitle: { fontSize: 15, fontWeight: '800', color: Colors.textPrimary, marginTop: 12 },
  emptySub: { fontSize: 12, color: Colors.textSecondary, textAlign: 'center', marginTop: 4, paddingHorizontal: 32 },
  customerCard: { backgroundColor: Colors.surface, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', ...Shadows.soft },
  cardHeader: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0, 109, 119, 0.1)', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  avatarText: { fontSize: 13, fontWeight: '800', color: Colors.primary },
  customerMeta: { flex: 1 },
  customerName: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary },
  customerId: { fontSize: 10, color: Colors.textSecondary, marginTop: 2 },
  segmentBadge: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 10 },
  segmentText: { fontSize: 10, fontWeight: '700' },
  detailsGrid: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: Colors.border, marginTop: 12, paddingTop: 12, gap: 16 },
  detailCell: { flexDirection: 'row', alignItems: 'center' },
  detailLabel: { fontSize: 11, color: Colors.textSecondary, marginRight: 4 },
  detailValue: { fontSize: 12, fontWeight: '700', color: Colors.textPrimary },
  cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: Colors.border, marginTop: 12, paddingTop: 12 },
  lastOrderDate: { fontSize: 11, color: Colors.textSecondary, fontWeight: '500' },
  actionButtons: { flexDirection: 'row', gap: 8 },
  actionBtn: { width: 32, height: 32, borderRadius: 10, borderWidth: 1, borderColor: Colors.primary, justifyContent: 'center', alignItems: 'center', backgroundColor: Colors.background },
});
