import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.surface },
  backButton: { padding: 8, marginRight: 8, borderRadius: 12, backgroundColor: Colors.background },
  headerText: { flex: 1 },
  title: { fontSize: 18, fontWeight: '800', color: Colors.textPrimary },
  subtitle: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  scrollContent: { padding: 16 },
  statsBanner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', backgroundColor: Colors.surface, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', borderRadius: 20, paddingVertical: 14, marginBottom: 24, ...Shadows.soft },
  statBox: { alignItems: 'center', flex: 1 },
  statLabel: { fontSize: 9, fontWeight: '700', color: Colors.textSecondary, letterSpacing: 0.5 },
  statVal: { fontSize: 18, fontWeight: '800', marginTop: 4 },
  statDivider: { width: 1, height: 24, backgroundColor: Colors.border },
  directoryHeader: { fontSize: 15, fontWeight: '800', color: Colors.textPrimary, marginBottom: 12 },
  ticketsList: { gap: 10 },
  ticketCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: Colors.surface, borderWidth: 1, borderColor: 'rgba(228, 231, 236, 0.5)', padding: 16, borderRadius: 20, ...Shadows.soft },
  row: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  ticketCat: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
  statusBadge: { paddingVertical: 2, paddingHorizontal: 6, borderRadius: 8 },
  statusText: { fontSize: 9, fontWeight: '800' },
  ticketId: { fontSize: 10, color: Colors.textSecondary, marginTop: 4, fontWeight: '600' },
  ticketCustomer: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  actionBlock: { alignItems: 'flex-end', gap: 8 },
  chatBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, borderWidth: 1, borderColor: Colors.primary, borderRadius: 10, paddingVertical: 5, paddingHorizontal: 12, backgroundColor: Colors.background },
  chatBtnText: { fontSize: 11, fontWeight: '700' },
  resolveLink: { paddingVertical: 2 },
  resolveLinkText: { fontSize: 11, fontWeight: '700', color: Colors.success },
  chatOverviewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: Colors.border, backgroundColor: Colors.background },
  chatOverviewTitle: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary },
  chatOverviewSub: { fontSize: 11, color: Colors.textSecondary, marginTop: 2 },
  chatTimeline: { flex: 1, backgroundColor: Colors.background },
  systemMessageContainer: { alignSelf: 'center', backgroundColor: 'rgba(102, 112, 133, 0.06)', paddingVertical: 4, paddingHorizontal: 10, borderRadius: 8, marginVertical: 4 },
  systemMessageText: { fontSize: 9, color: Colors.textSecondary, fontWeight: '600', textAlign: 'center' },
  chatBubbleContainer: { flexDirection: 'row', width: '100%', marginVertical: 4 },
  alignLeft: { justifyContent: 'flex-start' },
  alignRight: { justifyContent: 'flex-end' },
  chatBubble: { borderRadius: 16, padding: 10, maxWidth: '85%', ...Shadows.soft },
  bubbleCustomer: { backgroundColor: Colors.surface, borderTopLeftRadius: 4 },
  bubbleMerchant: { backgroundColor: Colors.primary, borderTopRightRadius: 4 },
  bubbleSender: { fontSize: 9, fontWeight: '700', marginBottom: 4 },
  bubbleBody: { fontSize: 12, lineHeight: 16, fontWeight: '500' },
  chatEntryBar: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 12, borderTopWidth: 1, borderTopColor: Colors.border, backgroundColor: Colors.surface, gap: 8, alignItems: 'center' },
  chatInput: { flex: 1, borderWidth: 1, borderColor: Colors.border, borderRadius: 12, paddingHorizontal: 12, height: 40, fontSize: 13, color: Colors.textPrimary, backgroundColor: Colors.background },
  sendBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: Colors.primary, alignItems: 'center', justifyContent: 'center' },
  chatClosedBanner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: 'rgba(34, 181, 115, 0.06)', paddingVertical: 12, borderTopWidth: 1, borderTopColor: Colors.border },
  chatClosedText: { fontSize: 11, fontWeight: '700', color: Colors.success },
});
