import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.surface },
  kav: { flex: 1 },
  scroll: { flexGrow: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingVertical: 12,
  },
  backBtn: {
    width: 40, height: 40, borderRadius: 12,
    backgroundColor: Colors.background,
    alignItems: 'center', justifyContent: 'center',
  },
  stepIndicator: { flexDirection: 'row', gap: 6, alignItems: 'center' },
  stepDot: { width: 24, height: 4, borderRadius: 2, backgroundColor: Colors.primary },
  stepDotInactive: { width: 8, height: 4, borderRadius: 2, backgroundColor: Colors.border },
  content: { paddingHorizontal: 28, paddingTop: 16, paddingBottom: 32 },
  eyebrow: {
    fontSize: 12, fontWeight: '700', color: Colors.primary,
    letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 12,
  },
  title: {
    fontSize: 28, fontWeight: '800', color: Colors.textPrimary,
    lineHeight: 36, letterSpacing: -0.5, marginBottom: 6,
  },
  subtitle: { fontSize: 15, color: Colors.textSecondary, lineHeight: 22, marginBottom: 32 },
  fieldGroup: { gap: 24 },
  fieldLabel: {
    fontSize: 12, fontWeight: '600', color: Colors.textSecondary,
    marginBottom: 10, letterSpacing: 0.3,
  },
  categorySelectorBtn: {
    height: 52, borderWidth: 1.5, borderColor: Colors.border,
    borderRadius: 14, paddingHorizontal: 16,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: Colors.surface,
  },
  categorySelectorFilled: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  categorySelectorContent: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  categoryEmoji: { fontSize: 18 },
  categorySelectorText: { fontSize: 15, color: Colors.textMuted, fontWeight: '500' },
  categorySelectorTextFilled: { color: Colors.textPrimary, fontWeight: '600' },
  addressInput: {
    height: 52, borderWidth: 1.5, borderColor: Colors.border,
    borderRadius: 14, paddingHorizontal: 16,
    fontSize: 15, fontWeight: '500', color: Colors.textPrimary,
    backgroundColor: Colors.surface,
  },
  addressInputFocused: { borderColor: Colors.primary },
  locationBtn: {
    height: 52, borderWidth: 1.5, borderRadius: 14,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
  },
  locationBtnDefault: { borderColor: Colors.primary, backgroundColor: Colors.surface },
  locationBtnLoading: { borderColor: Colors.border, backgroundColor: Colors.background },
  locationBtnSuccess: { borderColor: Colors.success, backgroundColor: Colors.successBg },
  locationBtnText: { fontSize: 14, fontWeight: '700' },
  locationBtnTextDefault: { color: Colors.primary },
  locationBtnTextLoading: { color: Colors.textMuted },
  locationBtnTextSuccess: { color: Colors.success },
  orRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  orLine: { flex: 1, height: 1, backgroundColor: Colors.border },
  orText: { fontSize: 11, fontWeight: '600', color: Colors.textMuted },
  footer: { paddingHorizontal: 28, paddingTop: 8, paddingBottom: 8 },
  cta: {
    height: 56, borderRadius: 20, alignItems: 'center', justifyContent: 'center',
    backgroundColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25, shadowRadius: 10, elevation: 5,
  },
  ctaDisabled: { backgroundColor: Colors.border },
  ctaText: { fontSize: 16, fontWeight: '700', color: Colors.white },
  ctaTextDisabled: { color: Colors.textMuted },
  sheetCategoryList: { paddingHorizontal: 16, paddingBottom: 24, gap: 4 },
  sheetCategoryItem: {
    flexDirection: 'row', alignItems: 'center', gap: 14,
    paddingHorizontal: 16, paddingVertical: 14,
    borderRadius: 14, borderWidth: 1, borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  sheetCategorySelected: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight },
  sheetCategoryEmoji: { fontSize: 22 },
  sheetCategoryLabel: { fontSize: 15, fontWeight: '600', color: Colors.textPrimary, flex: 1 },
  sheetCategoryDesc: { fontSize: 12, color: Colors.textSecondary, marginTop: 2 },
  sheetCategoryCheck: {
    width: 22, height: 22, borderRadius: 11,
    backgroundColor: Colors.primary,
    alignItems: 'center', justifyContent: 'center',
  },
});
