import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.background },

  // Header
  header: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingBottom: 24,
    overflow: 'hidden',
    position: 'relative',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerBlob: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  liveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  liveText: {
    fontSize: 11,
    fontWeight: '800',
    color: Colors.white,
    letterSpacing: 0.6,
  },
  headerIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.13)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  notifBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: Colors.accent,
    borderWidth: 1.5,
    borderColor: Colors.primary,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: Colors.white,
    marginBottom: 14,
  },
  headerStats: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  headerStatItem: { flex: 1, alignItems: 'center' },
  headerStatVal: { fontSize: 17, fontWeight: '800', color: Colors.white },
  headerStatLbl: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.6)',
    marginTop: 2,
    fontWeight: '500',
  },
  headerStatDivider: {
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.18)',
    marginVertical: 4,
  },

  // Tabs
  tabsWrap: {
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
    paddingVertical: 10,
  },
  tabsScroll: { paddingHorizontal: 16, gap: 8 },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  tabActive: {
    backgroundColor: Colors.primaryLight,
    borderColor: 'rgba(15,143,95,0.25)',
  },
  tabDot: { width: 6, height: 6, borderRadius: 3 },
  tabText: { fontSize: 13, fontWeight: '500', color: Colors.textSecondary },
  tabTextActive: { color: Colors.primary, fontWeight: '800' },
  tabCount: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.background,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  tabCountActive: {
    backgroundColor: Colors.surface,
    borderColor: 'transparent',
  },
  tabCountText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textSecondary,
  },
  tabCountTextActive: { color: Colors.primary },

  // List
  list: { padding: 16, gap: 10 },

  // Order card
  orderCard: {
    backgroundColor: Colors.surface,
    borderRadius: 18,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadows.card,
  },
  orderCardNew: {
    borderLeftWidth: 3,
    borderLeftColor: Colors.accent,
  },
  newOrderBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: -4,
  },
  newOrderDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.accent,
  },
  newOrderText: {
    fontSize: 10,
    fontWeight: '800',
    color: Colors.accent,
    letterSpacing: 0.8,
  },
  cardTopRow: { flexDirection: 'row', alignItems: 'center' },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: 16, fontWeight: '800', color: Colors.primary },
  customerName: { fontSize: 15, fontWeight: '700', color: Colors.textPrimary },
  orderMeta: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
  amount: { fontSize: 16, fontWeight: '800', color: Colors.textPrimary },
  payPill: {
    marginTop: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  payPillCOD: { backgroundColor: Colors.kpiAmberBg },
  payPillOnline: { backgroundColor: Colors.successBg },
  payPillText: { fontSize: 11, fontWeight: '700' },
  payPillTextCOD: { color: Colors.warning },
  payPillTextOnline: { color: Colors.success },
  chipsRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: Colors.surfaceElevated,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  chipText: { fontSize: 11, fontWeight: '500', color: Colors.textSecondary },
  urgencyChip: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
  },
  divider: { height: 1, backgroundColor: Colors.borderLight },
  actionsRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  acceptBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.primary,
    borderRadius: 16,
    paddingVertical: 13,
    ...Shadows.soft,
  },
  acceptBtnText: { fontSize: 14, fontWeight: '700', color: Colors.white },
  rejectBtn: {
    minWidth: '30%',
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rejectBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  viewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 12,
    paddingVertical: 13,
    borderRadius: 16,
    backgroundColor: Colors.primaryLight,
  },
  viewBtnText: { fontSize: 13, fontWeight: '600', color: Colors.primary },
  donePill: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    borderRadius: 14,
  },
  donePillGreen: { backgroundColor: Colors.successBg },
  donePillRed: { backgroundColor: Colors.errorBg },
  donePillText: { fontSize: 13, fontWeight: '700' },

  // Empty state
  emptyWrap: {
    alignItems: 'center',
    paddingVertical: 56,
    gap: 10,
  },
  emptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: Colors.textPrimary },
  emptySubtitle: {
    fontSize: 13,
    color: Colors.textMuted,
    textAlign: 'center',
    paddingHorizontal: 40,
    lineHeight: 20,
  },

  // Bottom sheet — order detail
  sheet: { padding: 20, gap: 4 },
  sheetSection: {
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  sheetSectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  sheetSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  sheetName: { fontSize: 16, fontWeight: '700', color: Colors.textPrimary },
  sheetMeta: { fontSize: 13, color: Colors.textMuted, marginTop: 2 },
  addressRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    alignItems: 'flex-start',
  },
  addressText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: Colors.textSecondary,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  itemName: { flex: 1, fontSize: 13, color: Colors.textPrimary },
  itemPrice: { fontSize: 13, fontWeight: '600', color: Colors.textPrimary },
  itemTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  itemTotalLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  itemTotalValue: {
    fontSize: 15,
    fontWeight: '800',
    color: Colors.textPrimary,
  },
  timelineRow: { flexDirection: 'row', marginBottom: 12 },
  timelineDotWrap: { alignItems: 'center', width: 16 },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 3,
    backgroundColor: Colors.primary,
    borderWidth: 2,
    borderColor: Colors.primaryLight,
  },
  timelineLine: {
    flex: 1,
    width: 2,
    backgroundColor: Colors.border,
    marginTop: 4,
  },
  timelineStatus: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textPrimary,
  },
  timelineTime: { fontSize: 11, color: Colors.textMuted, marginTop: 2 },
  driverRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  driverAvatar: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverAvatarText: { fontSize: 15, fontWeight: '800', color: Colors.primary },
  driverName: { fontSize: 14, fontWeight: '700', color: Colors.textPrimary },
  driverMeta: { fontSize: 12, color: Colors.textMuted, marginTop: 1 },
});
