import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  tabs: {
    flexDirection: 'row', gap: 6, paddingHorizontal: 16, paddingVertical: 10,
    backgroundColor: Colors.surface, borderBottomWidth: 1, borderBottomColor: Colors.border,
  },
  tab: { flex: 1, minHeight: 36, borderRadius: 8, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4 },
  tabActive: { backgroundColor: Colors.primaryLight },
  tabText: { fontSize: 11, fontWeight: '600', color: Colors.textSecondary },
  tabTextActive: { color: Colors.primaryDark },
  countPill: { minWidth: 16, height: 16, borderRadius: 50, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primary, paddingHorizontal: 4 },
  countPillText: { fontSize: 9, fontWeight: '700', color: Colors.white },
  list: { padding: 16, gap: 10 },
  emptyCard: { alignItems: 'center', gap: 6 },
  emptyTitle: { fontSize: 15, fontWeight: '600', color: Colors.textPrimary },
  emptyText: { fontSize: 12, fontWeight: '400', color: Colors.textSecondary, textAlign: 'center' },
  bargainCard: { gap: 10 },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  customerName: { fontSize: 15, fontWeight: '600', color: Colors.textPrimary },
  timerPill: { borderRadius: 50, paddingHorizontal: 10, paddingVertical: 4 },
  timerUrgent: { backgroundColor: Colors.errorBg },
  timerSafe: { backgroundColor: Colors.primaryLight },
  timerText: { fontSize: 12, fontWeight: '700' },
  timerTextUrgent: { color: '#C62828' },
  timerTextSafe: { color: '#1B5E20' },
  productName: { fontSize: 12, fontWeight: '400', color: Colors.textSecondary },
  offerRow: { paddingTop: 10, borderTopWidth: 1, borderTopColor: Colors.border },
  offerLabel: { fontSize: 12, fontWeight: '400', color: Colors.textSecondary },
  offerAmount: { fontSize: 15, fontWeight: '700', color: Colors.textPrimary },
  actions: { flexDirection: 'row', gap: 8 },
  actionBtn: { flex: 1 },
  alertSection: { marginTop: 8, gap: 8 },
  alertSectionTitle: { fontSize: 16, fontWeight: '600', color: Colors.textPrimary, marginBottom: 4 },
  alertCard: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#FFF8EE', borderRadius: 12, borderWidth: 1, borderColor: '#FFD59E', padding: 14, ...Shadows.soft },
  alertMeta: { flex: 1 },
  alertName: { fontSize: 13, fontWeight: '600', color: Colors.textPrimary },
  alertSub: { marginTop: 2, fontSize: 11, fontWeight: '400', color: Colors.textSecondary },
  sheet: { padding: 20, gap: 14 },
  sheetProduct: { fontSize: 15, fontWeight: '600', color: Colors.textPrimary },
  counterBox: { borderRadius: 12, backgroundColor: Colors.background, padding: 16, alignItems: 'center', borderWidth: 1, borderColor: Colors.border },
  counterLabel: { fontSize: 11, fontWeight: '600', color: Colors.textSecondary },
  counterPrice: { marginTop: 4, fontSize: 28, fontWeight: '700', color: Colors.textPrimary },
  counterActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  stepButton: { borderRadius: 8, backgroundColor: Colors.surface, borderWidth: 1, borderColor: Colors.border, paddingHorizontal: 18, paddingVertical: 9 },
  stepButtonActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  stepText: { fontSize: 13, fontWeight: '600', color: Colors.textPrimary },
  stepTextActive: { color: Colors.white },
  marginCard: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  marginText: { fontSize: 13, fontWeight: '600', color: Colors.textPrimary },
  chat: { padding: 16, paddingBottom: 24, gap: 12 },
  bubble: { alignSelf: 'flex-start', maxWidth: '78%', borderRadius: 18, borderBottomLeftRadius: 4, backgroundColor: '#F0F2F1', padding: 12 },
  bubbleMerchant: { alignSelf: 'flex-end', borderBottomLeftRadius: 18, borderBottomRightRadius: 4, backgroundColor: Colors.primary },
  bubbleSender: { fontSize: 10, fontWeight: '700', color: Colors.primaryDark, marginBottom: 3 },
  bubbleSenderMerchant: { color: 'rgba(255,255,255,0.75)' },
  bubbleBody: { fontSize: 13, lineHeight: 19, color: Colors.textPrimary },
  bubbleBodyMerchant: { color: Colors.white },
  priceChip: { alignSelf: 'flex-start', marginTop: 6, borderRadius: 50, backgroundColor: Colors.primaryLight, paddingHorizontal: 10, paddingVertical: 3, fontSize: 12, fontWeight: '700', color: Colors.primaryDark },
  priceChipMerchant: { backgroundColor: 'rgba(255,255,255,0.22)', color: Colors.white },
  bubbleTime: { marginTop: 5, fontSize: 10, color: Colors.textMuted },
  bubbleTimeMerchant: { color: 'rgba(255,255,255,0.55)', textAlign: 'right' },
  systemRow: { alignSelf: 'center', alignItems: 'center', gap: 2, marginVertical: 2 },
  systemText: { fontSize: 11, color: Colors.textMuted, textAlign: 'center' },
  systemTime: { fontSize: 10, color: Colors.textMuted, textAlign: 'center' },
  inputBar: { flexDirection: 'row', alignItems: 'flex-end', gap: 10, paddingHorizontal: 14, paddingVertical: 10, borderTopWidth: 1, borderTopColor: Colors.border, backgroundColor: Colors.surface },
  inputField: { flex: 1, minHeight: 42, maxHeight: 110, borderRadius: 22, borderWidth: 1, borderColor: Colors.border, backgroundColor: '#F0F2F1', paddingHorizontal: 16, paddingVertical: 10, fontSize: 14, color: Colors.textPrimary, lineHeight: 20 },
  sendBtn: { width: 42, height: 42, borderRadius: 21, backgroundColor: Colors.primary, alignItems: 'center', justifyContent: 'center' },
  sendBtnDisabled: { backgroundColor: Colors.border },
});
