import { StyleSheet } from "react-native";
import { Colors } from "../../theme/colors";
import { Shadows } from "../../theme/shadows";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: Colors.surface,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: Colors.textPrimary,
  },
  headerSubtitle: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 2,
    fontWeight: "500",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.background,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  addBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
    ...Shadows.soft,
  },
  headerAddButton: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
    ...Shadows.medium,
  },
  fab: {
    position: "absolute",
    right: 16,
    width: 56,
    height: 56,
    alignItems: "center",
    borderRadius: 28,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    ...Shadows.strong,
  },
  fabLabel: { fontSize: 14, fontWeight: "700", color: Colors.white },

  // ── Toast ─────────────────────────────────────────────────────────────────
  toastBanner: {
    position: "absolute",
    top: 90,
    left: 20,
    right: 20,
    zIndex: 50,
    backgroundColor: Colors.textPrimary,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    ...Shadows.soft,
  },
  toastText: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  toastError: { backgroundColor: Colors.error },

  // ── Search & filters ──────────────────────────────────────────────────────
  searchRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingTop: 12,
    gap: 10,
  },
  searchBox: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingHorizontal: 12,
    height: 48,
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadows.soft,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: Colors.textPrimary,
    paddingVertical: 0,
  },
  chipsRail: { height: 50, marginVertical: 10, marginTop: 10 },
  chipsScroll: { paddingHorizontal: 20, gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  chipActive: { backgroundColor: Colors.primaryLight, borderColor: "rgba(15,143,95,0.25)" },
  chipText: { fontSize: 12, fontWeight: "600", color: Colors.textSecondary },
  chipTextActive: { color: Colors.primary },

  // ── List & cards ──────────────────────────────────────────────────────────
  list: { paddingHorizontal: 20, paddingTop: 14, gap: 10 },
  productCard: {
    flexDirection: "row",
    backgroundColor: Colors.surface,
    borderRadius: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: "hidden",
    ...Shadows.card,
  },
  productCardInactive: { opacity: 0.62 },
  productImg: {
    width: 102,
    height: 116,
    borderRadius: 0,
    backgroundColor: Colors.background,
  },
  productImgPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  productInfo: { flex: 1, padding: 14, paddingLeft: 0 },
  commerceBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 8,
  },
  productNameRow: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  productName: {
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
    color: Colors.textPrimary,
  },
  productCat: { fontSize: 12, color: Colors.textMuted, marginTop: 3 },
  productBrand: {
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 1,
    fontWeight: "600",
  },
  badgeRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  pill: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
  },
  pillText: { fontSize: 10, fontWeight: "700" },
  loadMoreRow: { paddingVertical: 20, alignItems: "center" },

  // ── States (loading / empty / error) ─────────────────────────────────────
  skeletonCard: {
    flexDirection: "row",
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  skeletonBlock: { backgroundColor: Colors.border, borderRadius: 8 },
  stateWrap: {
    alignItems: "center",
    paddingVertical: 48,
    paddingHorizontal: 24,
  },
  stateIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: Colors.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  stateIconError: { backgroundColor: Colors.errorBg },
  stateTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.textPrimary,
    marginBottom: 6,
  },
  stateSub: {
    fontSize: 13,
    color: Colors.textMuted,
    textAlign: "center",
    lineHeight: 19,
    marginBottom: 16,
  },

  // ── Action sheet rows ─────────────────────────────────────────────────────
  sheetContent: { paddingHorizontal: 20, paddingTop: 4 },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  actionRowText: { fontSize: 14, fontWeight: "600", color: Colors.textPrimary },
  actionRowDanger: { color: Colors.error },
  confirmText: {
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 20,
    marginBottom: 18,
  },
  confirmActions: { flexDirection: "row", gap: 10 },

  // ── Product detail ────────────────────────────────────────────────────────
  detailScroll: { paddingHorizontal: 20, paddingTop: 14 },
  detailCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  detailTopRow: { flexDirection: "row", gap: 14 },
  detailImg: {
    width: 84,
    height: 84,
    borderRadius: 14,
    backgroundColor: Colors.background,
  },
  detailName: { fontSize: 18, fontWeight: "800", color: Colors.textPrimary },
  detailDesc: {
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 19,
    marginTop: 10,
  },
  metaGrid: { marginTop: 14, gap: 8 },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metaLabel: { fontSize: 12, color: Colors.textMuted, fontWeight: "500" },
  metaValue: {
    fontSize: 12,
    color: Colors.textPrimary,
    fontWeight: "600",
    maxWidth: "60%",
    textAlign: "right",
  },
  detailActions: { flexDirection: "row", gap: 10, marginTop: 14 },

  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    marginBottom: 10,
  },
  sectionHeaderTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.textPrimary,
  },

  variantCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: 10,
  },
  variantCardInactive: { opacity: 0.62 },
  variantTopRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  variantImg: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: Colors.background,
  },
  variantName: { fontSize: 14, fontWeight: "700", color: Colors.textPrimary },
  variantSub: { fontSize: 11, color: Colors.textMuted, marginTop: 1 },
  variantPriceRow: { flexDirection: "row", alignItems: "baseline", gap: 6 },
  variantPrice: { fontSize: 15, fontWeight: "800", color: Colors.textPrimary },
  variantMrp: {
    fontSize: 12,
    color: Colors.textMuted,
    textDecorationLine: "line-through",
  },
  variantMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    rowGap: 6,
  },
  variantMetaItem: { width: "50%" },
  variantMetaLabel: {
    fontSize: 10,
    color: Colors.textMuted,
    fontWeight: "600",
  },
  variantMetaValue: {
    fontSize: 12,
    color: Colors.textPrimary,
    fontWeight: "600",
    marginTop: 1,
  },
  variantActions: { flexDirection: "row", gap: 10, marginTop: 12 },
});
