import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Shadows } from '../../theme/shadows';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },

  header: {
    backgroundColor: Colors.surface,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: Colors.textPrimary,
    letterSpacing: -0.4,
  },
  headerSubtitle: {
    fontSize: 12,
    color: Colors.textMuted,
    marginTop: 2,
    fontWeight: '500',
  },
  headerSearchBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  addBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.soft,
  },

  healthStrip: {
    flexDirection: 'row',
    backgroundColor: Colors.background,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  healthItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    justifyContent: 'center',
  },
  healthDot: { width: 7, height: 7, borderRadius: 4 },
  healthVal: { fontSize: 15, fontWeight: '700', color: Colors.textPrimary },
  healthLbl: { fontSize: 11, color: Colors.textMuted, fontWeight: '500' },
  healthDivider: {
    width: 1,
    backgroundColor: Colors.borderLight,
    marginVertical: 4,
  },

  toastBanner: {
    position: 'absolute',
    top: 80,
    alignSelf: 'center',
    zIndex: 999,
    backgroundColor: Colors.textPrimary,
    borderRadius: 50,
    paddingHorizontal: 20,
    paddingVertical: 10,
    ...Shadows.strong,
  },
  toastText: { fontSize: 13, fontWeight: '600', color: Colors.white },

  segmentWrap: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  segmentTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  segmentTabActive: { borderBottomColor: Colors.primary },
  segmentText: { fontSize: 13, fontWeight: '500', color: Colors.textMuted },
  segmentTextActive: { color: Colors.primary, fontWeight: '700' },

  searchRow: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
  },
  searchBox: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: { flex: 1, fontSize: 14, color: Colors.textPrimary },
  filterBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },

  alertBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: Colors.kpiAmberBg,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: `${Colors.warning}30`,
  },
  alertBannerLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  alertBannerText: { fontSize: 13, fontWeight: '600', color: Colors.warning },

  chipsRail: { flexGrow: 0, flexShrink: 0 },
  chipsScroll: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 2,
  },
  chip: {
    height: 32,
    paddingHorizontal: 14,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  chipText: { fontSize: 13, fontWeight: '500', color: Colors.textSecondary },
  chipTextActive: { color: Colors.white, fontWeight: '600' },

  list: { padding: 16, gap: 10 },

  productCard: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    ...Shadows.card,
  },
  productImgWrap: {
    width: 125,
    height: 127,
    borderRadius: 12,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    position: 'relative',
  },
  productImg: {
    width: 120,
    height: '100%',
    borderRadius: 12,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
  productImgPlaceholder: {
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  statusDot: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 9,
    height: 9,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: Colors.white,
  },
  productInfo: { flex: 1, padding: 14 },
  productNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  productName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: Colors.textPrimary,
    lineHeight: 20,
  },
  productCat: {
    fontSize: 11,
    color: Colors.textMuted,
    marginTop: 1,
    marginBottom: 6,
  },
  productPriceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6 },
  productPrice: { fontSize: 15, fontWeight: '800', color: Colors.textPrimary },
  productMrp: {
    fontSize: 11,
    color: Colors.textMuted,
    textDecorationLine: 'line-through',
  },
  discountChip: {
    backgroundColor: Colors.primaryLight,
    borderRadius: 20,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  discountChipText: { fontSize: 10, fontWeight: '700', color: Colors.primary },
  productMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  productStock: { fontSize: 12, fontWeight: '600', color: Colors.textSecondary },
  productSold: { fontSize: 11, color: Colors.textMuted },
  dot: { width: 3, height: 3, borderRadius: 1.5, backgroundColor: Colors.border },
  statusPill: {
    marginLeft: 'auto',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
  },
  statusPillText: { fontSize: 10, fontWeight: '700' },

  emptyState: { alignItems: 'center', paddingTop: 60, gap: 10 },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  emptyTitle: { fontSize: 17, fontWeight: '700', color: Colors.textPrimary },
  emptySub: { fontSize: 13, color: Colors.textMuted, textAlign: 'center' },

  summaryRow: { flexDirection: 'row', gap: 10, marginBottom: 4 },
  summaryCard: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    ...Shadows.soft,
  },
  summaryVal: { fontSize: 22, fontWeight: '700', color: Colors.textPrimary },
  summaryLbl: { marginTop: 2, fontSize: 11, color: Colors.textMuted },
  stockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    ...Shadows.soft,
  },
  stockName: { fontSize: 14, fontWeight: '600', color: Colors.textPrimary },
  stockMeta: { marginTop: 2, fontSize: 11, color: Colors.textMuted },
  qtyBtn: {
    width: 38,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  qtyBtnPos: { backgroundColor: Colors.primaryLight, borderColor: Colors.primaryLight },
  qtyText: { fontSize: 12, fontWeight: '600', color: Colors.textSecondary },
  qtyTextPos: { color: Colors.primary },

  offerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 14,
    ...Shadows.soft,
  },
  createOfferBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.primary,
    borderStyle: 'dashed',
    padding: 14,
  },
  createOfferText: { fontSize: 14, fontWeight: '600', color: Colors.primary },

  // Modal
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
    backgroundColor: Colors.surface,
  },
  modalTitle: { fontSize: 16, fontWeight: '700', color: Colors.textPrimary },
  modalClose: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSaveSmall: {
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  modalSaveSmallText: { fontSize: 14, fontWeight: '700', color: Colors.white },

  modalForm: { padding: 20, gap: 0 },
  imageSectionWrap: { alignItems: 'center', marginBottom: 20 },
  imageUploadBox: {
    width: 96,
    height: 96,
    borderRadius: 16,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: Colors.borderLight,
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  imageUploadLabel: { fontSize: 12, color: Colors.textMuted },
  imageEditWrap: { position: 'relative' },
  imagePreview: { width: 96, height: 96, borderRadius: 16 },
  imageEditOverlay: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },

  formSectionLabelWrap: {
    paddingTop: 8,
    paddingBottom: 4,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
    marginTop: 12,
  },
  formSectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: Colors.textMuted,
  },

  fieldWrap: { flex: 1, marginBottom: 14 },
  fieldRow: { flexDirection: 'row', gap: 12 },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: 6,
  },
  fieldInput: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  fieldInputRow: { justifyContent: 'space-between' },
  fieldInputMulti: { alignItems: 'flex-start', paddingVertical: 10 },
  fieldInputError: { borderColor: Colors.error },
  fieldText: { flex: 1, fontSize: 14, color: Colors.textPrimary },
  fieldPlaceholder: { color: Colors.textMuted },
  fieldTextInput: { flex: 1, fontSize: 14, color: Colors.textPrimary, padding: 0 },
  fieldPrefix: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.textSecondary,
    marginRight: 4,
  },
  fieldError: { marginTop: 4, fontSize: 11, color: Colors.error },
  fieldHint: { marginTop: 4, fontSize: 11, color: Colors.textMuted },

  discountBadge: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.primaryLight,
    borderRadius: 50,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginBottom: 10,
  },
  discountBadgeText: { fontSize: 12, fontWeight: '600', color: Colors.primaryDark },
  warningBanner: {
    backgroundColor: Colors.warningBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: `${Colors.warning}40`,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 10,
  },
  warningText: { fontSize: 12, color: '#B45309', fontWeight: '500' },

  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  toggleTitle: { fontSize: 14, fontWeight: '600', color: Colors.textPrimary },
  toggleSub: { marginTop: 2, fontSize: 11, color: Colors.textMuted },

  deleteBtn: { marginTop: 28, alignSelf: 'center', paddingVertical: 10 },
  deleteBtnText: { fontSize: 14, fontWeight: '600', color: Colors.error },

  deleteSheet: { padding: 20, gap: 16 },
  deleteSheetSub: { fontSize: 14, color: Colors.textSecondary, lineHeight: 20 },
  deleteSheetActions: { flexDirection: 'row', gap: 12 },
  cancelSheetBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelSheetText: { fontSize: 14, fontWeight: '600', color: Colors.textSecondary },
  confirmDeleteBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: Colors.error,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmDeleteText: { fontSize: 14, fontWeight: '600', color: Colors.white },

  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  pickerSheet: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 36,
  },
  pickerTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textMuted,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  pickerRowActive: {
    backgroundColor: Colors.primaryLight,
    marginHorizontal: -20,
    paddingHorizontal: 20,
  },
  pickerRowText: { fontSize: 15, color: Colors.textPrimary },
  pickerRowTextActive: { fontWeight: '700', color: Colors.primary },
});
